# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: ANL Documentation
site_url: https://yasserfarouk.github.io/anl/
nav:
    - Index: index.md
    - Installation: install.md
    - Tutorial: tutorials/tutorial.md
    - FAQ: faq.md
    - Reference: reference.md
theme:
  name: "mkdocs"
plugins:
- search
- mkdocstrings
- include-markdown

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
